### ISSUE TITLE
remove static bower versioning, gittags are used instead

### ISSUE THREAD

**Issue by StudioSpindle** [dorel/dorel.github.io#101]
@bobvanluijt source?

**Comment by StudioSpindle** [comment]
Source: http://stackoverflow.com/questions/19456091/bower-register-new-version

**Comment by StudioSpindle** [comment]
remove versioning from bower file

**Comment by bobvanluijt** [comment]
> Your package must be available at a Git endpoint (e.g., GitHub); remember to push your Git tags!

http://stackoverflow.com/a/20055632/1501285
