### ISSUE TITLE
Architectural Diagram Polymer and Wordpress

### ISSUE THREAD

**Issue by bobvanluijt** [dorel/dorel.github.io#126]
### Description
@StudioSpindle and @mrpharderwijk, to align the above matter a bit better can you please create the following: an architectural diagram showing the general setup for the Polymer Elements and a workflow.

Diagram like: http://www.dorel.io/service-manual/use-technology/container-architecture.html

One thing it should also contain are 'extension types'.
1. New Element (and what rules apply)
2. Extension of Element (and what rules apply)
3. Extension of App (and what rules apply, also, include if it is a global scope addition or not)

Also, please include / create a second one for the Wordpress template.
Also, please include the appropriate repos etc.
Also, please include PRPL pattern, nomenclature etcetera.

Would be great if it can be added to Dorel.io for new people who will work on the platform.

**Comment by bobvanluijt** [comment]
@StudioSpindle also include the option we discussed over the phone in here (example: paper-card and the option to add a card in Wordpress)

**Comment by StudioSpindle** [comment]
Example: 
<paper-card heading="Emmental" image="http://placehold.it/350x150/FFC107/000000" alt="Emmental">
  <div class="card-content">
    Emmentaler or Emmental is a yellow, medium-hard cheese that originated in the area around Emmental, Switzerland. It is one of the cheeses of Switzerland, and is sometimes known as Swiss cheese.
  </div>
  <div class="card-actions">
    <paper-button>Share</paper-button>
    <paper-button>Explore!</paper-button>
  </div>
</paper-card>


In the diagram it needs to be visible that a element can be added as such markup in the Wordpress template, but ONLY the image and text is editable. So in Wordpress you have a option to click a '+' sign and that it's added.

**Comment by mrpharderwijk** [comment]
**Wordpress Requirements**
- Open Source heeft voorkeur over closed source
- Moet installeerbaar zijn middels `wp-cli`
- In lijn met de ecosytem/platform strategy van Dorel.io

**Comment by mrpharderwijk** [comment]
Currently diagram wp in progress https://www.draw.io/?state=%7B%22ids%22:%5B%220B2aBw2TXNtAOYm8zeGZoYjk5MTA%22%5D,%22action%22:%22open%22,%22userId%22:%22103369087994044599530%22%7D#G0B2aBw2TXNtAOYm8zeGZoYjk5MTA

**Comment by StudioSpindle** [comment]
Moved this over to https://djgusa.atlassian.net/browse/DIO-9
