### ISSUE TITLE
Create kitchensink with all polymer elements

### ISSUE THREAD

**Issue by StudioSpindle** [dorel/dorel.github.io#19]
### Description

Add elements from https://elements.polymer-project.org/elements/ to single kitchensink file to have an overview of usable components. This can be used to style the elements.
### Expected outcome

Single page with all the elements.
### Steps to reproduce (if applicable)

dorel.io/kitchensink.html

**Comment by StudioSpindle** [comment]
@bobvanluijt FYI

**Comment by bobvanluijt** [comment]
As a note, maybe make the page dynamic?

**Comment by StudioSpindle** [comment]
Feature Request: Dynamic in the sense that there is a dropdown where you can select a brand. Once you select a brand, the styling of the entire page changes to the corresponding brand styling. 

Action: Create separate (related) task for this.
