### ISSUE TITLE
Confusing folder structure

### ISSUE THREAD

**Issue by bobvanluijt** [dorel/dorel.github.io#21]
### Description

Currently, we have folders in the /source/site like https://github.com/dorel/dorel.github.io/tree/develop/source/site/_helping-people-to-use-your-service
But we also have folders in /source/site/_service-manual like: https://github.com/dorel/dorel.github.io/tree/develop/source/site/_service-manual

### Expected outcome

Probably all in /source/site _or_ all in /source/site/_service-manual

**Comment by StudioSpindle** [comment]
@bobvanluijt https://github.com/dorel/dorel.github.io/tree/develop/source/site/_helping-people-to-use-your-service is incorrect and can be removed.

**Comment by bobvanluijt** [comment]
We have many more folders like this. This was just an example

**Comment by StudioSpindle** [comment]
Seems that the folders have been mixed up. All the folders need to be in the root of /source/site. 

Will re-work this in this ticket.

**Comment by StudioSpindle** [comment]
merged
