### ISSUE TITLE
Create documentation on JS code conventions

### ISSUE THREAD

**Issue by StudioSpindle** [dorel/dorel.github.io#4]

**Comment by bobvanluijt** [comment]
It is important that we first have the architecture ready. (see the feature branch 'architecture')

@StudioSpindle feedback would be great so we can integrate this asap.

**Comment by StudioSpindle** [comment]
Agreed. Reviewed it and merged. Architecture is in place.

**Comment by mrpharderwijk** [comment]
Regarding conventions and code styling I would suggest implementing JShint and ESlint (through Grunt or Gulp). As far as physical documentation I will refer to Googles https://google.github.io/styleguide/javascriptguide.xml. I will create a JS documentation page where I will elaborate on this javascript guide.

**Comment by mrpharderwijk** [comment]
I've read into the Polymer CLI and discovered there is an polymer linting tool (https://github.com/PolymerLabs/polylint). I will dive into if we can use this extensively for our JS as well as css linting

**Comment by StudioSpindle** [comment]
Added in JIRA: https://djgusa.atlassian.net/browse/DIO-12
