### ISSUE TITLE
Check browser rendering IE and Safari

### ISSUE THREAD

**Issue by bobvanluijt** [dorel/dorel.github.io#76]
### Description
Safari doesn't render correctly

**Comment by StudioSpindle** [comment]
- SVG logo bounding image bug
- homepage manual lists stacking issue

![schermafbeelding 2016-10-26 om 12 22 07](https://cloud.githubusercontent.com/assets/9882035/19722399/d818390e-9b76-11e6-9765-83aa0f75291e.png)

**Comment by StudioSpindle** [comment]
Firefox on windows is fine
