### ISSUE TITLE
Update website to guidelines document

### ISSUE THREAD

**Issue by bobvanluijt** [dorel/dorel.github.io#97]
### Description
Update website to guidelines document

**Comment by bobvanluijt** [comment]
@StudioSpindle send documentation in email

**Comment by StudioSpindle** [comment]
@bobvanluijt You mean the fonts, colors and copy that will need to be adjusted? 

Do you perhaps have a folder containing all the assets such as the logo as .eps etc?

**Comment by StudioSpindle** [comment]
Link to dorel guidelines: https://drive.google.com/open?id=0B_6UvL74WpZdMzJITXIxSDZGNFE

**Comment by bobvanluijt** [comment]
@StudioSpindle Let me figure that out for you
